name: Time to Bake...
on: 
  #releasepush:
    #pushbuild
  watch: 
      types: [started]
env:
  ROM_URL: https://netix.dl.sourceforge.net/project/kyvangka-build/Nusantara_v2.5-11-ginkgo-27122020-UNOFFICIAL-0523.zip
  ROM_NAME: Generic:Nusantara_v2-5
  FIRMWAREZIPNAME: Nusantara_v2.5-11-ginkgo-27122020-UNOFFICIAL-0523.zip
  ZIP_NAME: Nusantara_v2-5
  SCRIPT_NAME: sha010
  SECRETS_PASSWORD: ${{ secrets.SFGPASS }}
  TZ: Middle-East/Kuwait
  SFDIRA1: cd /home/pfs/project/berkay-gsi/NusantaraProject
  SFDIRA2: cd /home/pfs/project/berkay-gsi/berkay
  SFUSER: ${{ secrets.SFUSER }}

jobs:
    build:
       runs-on: ubuntu-latest
    
       steps:
        - name: Checkout
          uses: actions/checkout@main
       
           
        - name: Setting up the SPICES
          run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
            sudo -E apt-get -qq install python3
            sudo -E apt-get -qq install simg2img
            sudo apt-get install -y expect
            expect -c " 
            spawn git clone ${{ secrets.TOPSECRET }} ErfanGSIs
            expect \"Username\"        
            send \"${{ secrets.GHUSER }}\r\"
            expect \"Password\"        
            send \"${{ secrets.GHPASS }}\r\"
            expect \"Password\"        
            send \"${{ secrets.GHPASS }}\r\"
            set timeout -1
            catch wait result
            interact"
            sudo chmod -R 777 ErfanGSIs
            cd ErfanGSIs
            sudo bash setup.sh
             
        - name: Make Dynamic GSI
          run: cd ErfanGSIs && sudo ./url2GSI.sh $ROM_URL $ROM_NAME -d  
       
        - name: Zipping BOTH COOKIES
          run: |
              mkdir final
              sudo chmod -R 777 ErfanGSIs/output
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-Aonly.7z ErfanGSIs/output/*-Aonly-*.img 
              zip -r ErfanGSIs/output/$ZIP_NAME-GSI-AB.7z ErfanGSIs/output/*-AB-*.img
              
        - name: uploading to bekay-gsi
          run: |   
              cd ErfanGSIs/output
              expect -c " 
              spawn sftp berkay-gsi@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFGPASS }}\r\"
              expect \"sftp> \"
              send \"$SFDIRA2\r\"
              set timeout -1
              send \"put *-Aonly-*.txt\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              interact"
              expect -c "
              spawn sftp berkay-gsi@frs.sourceforge.net
              expect \"Password\"
              send \"${{ secrets.SFGPASS }}\r\"
              expect \"sftp> \"
              send \"$SFDIRA1\r\"
              set timeout -1
              send \"put $ZIP_NAME-GSI-Aonly.7z\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              interact"
              expect -c "
              spawn sftp berkay-gsi@frs.sourceforge.net
              expect \"Password\"
              send \"${{ secrets.SFGPASS }}\r\"
              expect \"sftp> \"
              send \"$SFDIRA1\r\"
              set timeout -1
              send \"put $ZIP_NAME-GSI-AB.7z\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"
